import type { Workspace, Domain } from "./types"

export const initialDomains: Domain[] = [
  {
    id: "dom-1",
    name: "Nivel de Satisfaccion",
    description: "Niveles estandar de satisfaccion para encuestas",
    values: [
      { id: "dv-1", domainId: "dom-1", label: "Muy Insatisfecho", value: "1" },
      { id: "dv-2", domainId: "dom-1", label: "Insatisfecho", value: "2" },
      { id: "dv-3", domainId: "dom-1", label: "Neutral", value: "3" },
      { id: "dv-4", domainId: "dom-1", label: "Satisfecho", value: "4" },
      { id: "dv-5", domainId: "dom-1", label: "Muy Satisfecho", value: "5" },
    ],
  },
  {
    id: "dom-2",
    name: "Prioridad",
    description: "Niveles de prioridad para clasificacion",
    values: [
      { id: "dv-6", domainId: "dom-2", label: "Baja", value: "low" },
      { id: "dv-7", domainId: "dom-2", label: "Media", value: "medium" },
      { id: "dv-8", domainId: "dom-2", label: "Alta", value: "high" },
      { id: "dv-9", domainId: "dom-2", label: "Critica", value: "critical" },
    ],
  },
  {
    id: "dom-3",
    name: "Departamento",
    description: "Departamentos de la organizacion",
    values: [
      { id: "dv-10", domainId: "dom-3", label: "Recursos Humanos", value: "hr" },
      { id: "dv-11", domainId: "dom-3", label: "Tecnologia", value: "tech" },
      { id: "dv-12", domainId: "dom-3", label: "Ventas", value: "sales" },
      { id: "dv-13", domainId: "dom-3", label: "Marketing", value: "marketing" },
      { id: "dv-14", domainId: "dom-3", label: "Finanzas", value: "finance" },
    ],
  },
  {
    id: "dom-4",
    name: "Frecuencia",
    description: "Opciones de frecuencia temporal",
    values: [
      { id: "dv-15", domainId: "dom-4", label: "Diario", value: "daily" },
      { id: "dv-16", domainId: "dom-4", label: "Semanal", value: "weekly" },
      { id: "dv-17", domainId: "dom-4", label: "Mensual", value: "monthly" },
      { id: "dv-18", domainId: "dom-4", label: "Anual", value: "yearly" },
    ],
  },
]

export const initialWorkspaces: Workspace[] = [
  {
    id: "ws-1",
    name: "Recursos Humanos",
    description: "Formularios del departamento de RRHH para evaluaciones, encuestas y procesos internos",
    color: "#0ea5e9",
    icon: "Users",
    forms: [
      {
        id: "form-1",
        workspaceId: "ws-1",
        name: "Evaluacion de Desempeno",
        description: "Formulario trimestral de evaluacion del desempeno de empleados",
        status: "published",
        createdAt: "2026-01-15T10:00:00Z",
        updatedAt: "2026-02-10T14:30:00Z",
        sections: [
          {
            id: "sec-1",
            formId: "form-1",
            title: "Datos del Empleado",
            description: "Informacion basica del empleado evaluado",
            order: 0,
            questions: [
              {
                id: "q-1",
                sectionId: "sec-1",
                type: "text",
                label: "Nombre completo del empleado",
                required: true,
                order: 0,
                config: { placeholder: "Ingrese el nombre completo" },
              },
              {
                id: "q-2",
                sectionId: "sec-1",
                type: "select",
                label: "Departamento",
                required: true,
                order: 1,
                domainId: "dom-3",
                config: {},
              },
              {
                id: "q-3",
                sectionId: "sec-1",
                type: "date",
                label: "Fecha de ingreso",
                required: true,
                order: 2,
                config: {},
              },
            ],
          },
          {
            id: "sec-2",
            formId: "form-1",
            title: "Rendimiento",
            description: "Evaluacion del rendimiento laboral",
            order: 1,
            questions: [
              {
                id: "q-4",
                sectionId: "sec-2",
                type: "rating",
                label: "Calidad del trabajo",
                description: "Evalue la calidad general del trabajo realizado",
                required: true,
                order: 0,
                config: { stars: 5 },
              },
              {
                id: "q-5",
                sectionId: "sec-2",
                type: "scale",
                label: "Puntualidad",
                description: "Evalue la puntualidad del empleado",
                required: true,
                order: 1,
                config: { scaleMin: 1, scaleMax: 10, scaleMinLabel: "Deficiente", scaleMaxLabel: "Excelente" },
              },
              {
                id: "q-6",
                sectionId: "sec-2",
                type: "text",
                label: "Comentarios adicionales",
                required: false,
                order: 2,
                config: { placeholder: "Escriba sus comentarios..." },
              },
            ],
          },
        ],
      },
      {
        id: "form-2",
        workspaceId: "ws-1",
        name: "Encuesta de Clima Laboral",
        description: "Encuesta anual para medir el ambiente de trabajo",
        status: "draft",
        createdAt: "2026-02-01T08:00:00Z",
        updatedAt: "2026-02-18T16:45:00Z",
        sections: [
          {
            id: "sec-3",
            formId: "form-2",
            title: "Satisfaccion General",
            order: 0,
            questions: [
              {
                id: "q-7",
                sectionId: "sec-3",
                type: "select",
                label: "Nivel de satisfaccion con su puesto",
                required: true,
                order: 0,
                domainId: "dom-1",
                config: {},
              },
              {
                id: "q-8",
                sectionId: "sec-3",
                type: "boolean",
                label: "Recomendaria la empresa como lugar de trabajo?",
                required: true,
                order: 1,
                config: {},
              },
              {
                id: "q-9",
                sectionId: "sec-3",
                type: "multi-select",
                label: "Areas que necesitan mejora",
                description: "Seleccione todas las que apliquen",
                required: false,
                order: 2,
                domainId: "dom-3",
                config: {},
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "ws-2",
    name: "Control de Calidad",
    description: "Formularios para inspecciones, auditorias y control de calidad de productos",
    color: "#10b981",
    icon: "ClipboardCheck",
    forms: [
      {
        id: "form-3",
        workspaceId: "ws-2",
        name: "Inspeccion de Producto",
        description: "Lista de verificacion para inspeccion de calidad de productos",
        status: "published",
        createdAt: "2026-01-20T09:00:00Z",
        updatedAt: "2026-02-15T11:20:00Z",
        sections: [
          {
            id: "sec-4",
            formId: "form-3",
            title: "Identificacion del Producto",
            order: 0,
            questions: [
              {
                id: "q-10",
                sectionId: "sec-4",
                type: "text",
                label: "Codigo del producto",
                required: true,
                order: 0,
                config: { placeholder: "Ej: PROD-001" },
              },
              {
                id: "q-11",
                sectionId: "sec-4",
                type: "number",
                label: "Cantidad inspeccionada",
                required: true,
                order: 1,
                config: { min: 1, max: 10000 },
              },
              {
                id: "q-12",
                sectionId: "sec-4",
                type: "file",
                label: "Foto del producto",
                description: "Adjunte una foto del producto inspeccionado",
                required: false,
                order: 2,
                config: { accept: "image/*" },
              },
            ],
          },
          {
            id: "sec-5",
            formId: "form-3",
            title: "Evaluacion de Calidad",
            order: 1,
            questions: [
              {
                id: "q-13",
                sectionId: "sec-5",
                type: "matrix",
                label: "Evaluacion por criterio",
                description: "Evalue cada aspecto del producto",
                required: true,
                order: 0,
                config: {
                  matrixRows: ["Apariencia", "Funcionalidad", "Resistencia", "Acabado"],
                  matrixColumns: ["Deficiente", "Regular", "Bueno", "Excelente"],
                },
              },
              {
                id: "q-14",
                sectionId: "sec-5",
                type: "select",
                label: "Nivel de prioridad del defecto",
                required: false,
                order: 1,
                domainId: "dom-2",
                config: {},
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "ws-3",
    name: "Atencion al Cliente",
    description: "Formularios de feedback, encuestas post-servicio y seguimiento",
    color: "#f59e0b",
    icon: "Headphones",
    forms: [
      {
        id: "form-4",
        workspaceId: "ws-3",
        name: "Feedback Post-Servicio",
        description: "Encuesta rapida despues de atencion al cliente",
        status: "published",
        createdAt: "2026-02-05T12:00:00Z",
        updatedAt: "2026-02-20T09:15:00Z",
        sections: [
          {
            id: "sec-6",
            formId: "form-4",
            title: "Evaluacion del Servicio",
            order: 0,
            questions: [
              {
                id: "q-15",
                sectionId: "sec-6",
                type: "rating",
                label: "Calificacion general del servicio",
                required: true,
                order: 0,
                config: { stars: 5 },
              },
              {
                id: "q-16",
                sectionId: "sec-6",
                type: "select",
                label: "Frecuencia de uso del servicio",
                required: true,
                order: 1,
                domainId: "dom-4",
                config: {},
              },
              {
                id: "q-17",
                sectionId: "sec-6",
                type: "text",
                label: "Que podemos mejorar?",
                required: false,
                order: 2,
                config: { placeholder: "Comparta sus sugerencias..." },
              },
            ],
          },
        ],
      },
      {
        id: "form-5",
        workspaceId: "ws-3",
        name: "Registro de Incidencias",
        description: "Formulario para reportar incidencias de servicio",
        status: "draft",
        createdAt: "2026-02-12T15:00:00Z",
        updatedAt: "2026-02-19T10:30:00Z",
        sections: [
          {
            id: "sec-7",
            formId: "form-5",
            title: "Datos de la Incidencia",
            order: 0,
            questions: [
              {
                id: "q-18",
                sectionId: "sec-7",
                type: "text",
                label: "Titulo de la incidencia",
                required: true,
                order: 0,
                config: { placeholder: "Describa brevemente la incidencia" },
              },
              {
                id: "q-19",
                sectionId: "sec-7",
                type: "select",
                label: "Prioridad",
                required: true,
                order: 1,
                domainId: "dom-2",
                config: {},
              },
              {
                id: "q-20",
                sectionId: "sec-7",
                type: "date",
                label: "Fecha del incidente",
                required: true,
                order: 2,
                config: {},
              },
            ],
          },
        ],
      },
    ],
  },
]
